language: cpp

compiler:
- gcc
- clang
os:
 - linux

jobs:
  include:
  - name: "all projects"

script:
    - cmake -H. -B_build
    - cmake --build _build
    - name: "each CMakeLists.txt"
    - cpack /_build/-G TGZ
    - cpack /_build/-G DEB

addons:
  apt:
    sources:
      - george-edison55-precise-backports
    packages:
      - cmake
      - cmake-data

